//------------------------------------------------------------------------
// Copyright(c) 2024 Toby Corp.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"FFTPitchShift.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"FFTPitchShift VST3 (64Bit)"
#else
#define stringFileDescription	"FFTPitchShift VST3"
#endif
#define stringCompanyName		"Toby Corp\0"
#define stringLegalCopyright	"Copyright(c) 2024 Toby Corp."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
